# Generated by Django 5.0.6 on 2024-06-23 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('No Active', 'No Active')], max_length=50)),
                ('Phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Camera_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.camera')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='Active',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.security'),
        ),
    ]
