# Generated by Django 5.0.6 on 2024-06-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_camera_active_alter_security_camera_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='Status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'No Active')], max_length=50),
        ),
    ]
