# Generated by Django 5.0.6 on 2024-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_security_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'No Active')]),
        ),
    ]
