# Generated by Django 5.0.6 on 2024-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_security_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('No Active', 'No Active')], max_length=50),
        ),
    ]
